using System;
using System.IO;
using System.Text;
using System.Xml;
using System.Linq;
using System.Collections.Generic;
using System.Windows.Forms;
internal static class SpecialTrial {
 internal static bool Active,Hit,Guard;internal static DebugFrame Latest;internal static readonly HashSet<int> Actions=new HashSet<int>();static DebugFrame previous;
 internal static void Begin(DebugFrame f){if(ValidationSession.Armed)throw new InvalidOperationException("Finish the current trial first.");ValidationSession.Begin(f,0);Active=true;Hit=Guard=false;Actions.Clear();Latest=f;previous=f;}
 internal static void Observe(DebugFrame f){if(!Active||!ValidationSession.Armed)return;Latest=f;var c=f.Meter.Players[0];if(c.LastExecution!=null&&c.LastExecution.Capture>ValidationSession.Start)Actions.Add(c.LastExecution.Action);
  if(previous!=null&&previous.Readiness!=null&&f.Readiness!=null&&previous.Readiness.Length==20&&f.Readiness.Length==20){Hit|=f.Readiness[2]==2&&f.Readiness[14]<previous.Readiness[14];Guard|=f.Readiness[2]==1&&(f.Readiness[13]&32)!=0;}
  previous=f;
 }
 internal static string Result(string scenario,bool complete){if(ValidationSession.Broken)return "INVALID_CAPTURE";if(Actions.Count==0)return "NOT_EXECUTED";if(scenario=="Whiff"&&(Hit||Guard)||scenario=="Block"&&Hit||scenario=="Hit"&&Guard)return "WRONG_SCENARIO";if(scenario=="Block"&&!Guard||scenario=="Hit"&&!Hit)return "NO_CONTACT";return complete?"EXECUTED_UNVERIFIED":"DETECTION_INCOMPLETE";}
}
internal sealed class SpecialQueueForm:Form {
 readonly XmlDocument db=new XmlDocument();readonly ComboBox characters=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=210},scenario=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=100};readonly ListBox moves=new ListBox{Dock=DockStyle.Left,Width=420};readonly TextBox detail=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill};XmlElement armed;string armedScenario;
 sealed class Item{internal XmlElement Node;public override string ToString(){return Node.GetAttribute("name")+"  ["+Node.GetAttribute("input")+"]";}}
 internal SpecialQueueForm(){Text="Special-move testing - assisted / runtime evidence required";Width=1100;Height=650;db.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"special-moves.xml"));var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=70};top.Controls.Add(characters);top.Controls.Add(scenario);scenario.Items.AddRange(new[]{"Whiff","Block","Hit"});scenario.SelectedIndex=0;
  var begin=new Button{Text="Begin recording",AutoSize=true};var finish=new Button{Text="Finish + save",AutoSize=true};var next=new Button{Text="Next untested",AutoSize=true};top.Controls.Add(begin);top.Controls.Add(finish);top.Controls.Add(next);Controls.Add(detail);Controls.Add(moves);Controls.Add(top);
  var names=db.SelectNodes("/SpecialDatabase/Move").Cast<XmlElement>().Select(x=>x.GetAttribute("character")).Distinct().OrderBy(x=>x=="Kim Kaphwan"?0:1).ThenBy(x=>x).ToArray();characters.Items.AddRange(names);
  characters.SelectedIndexChanged+=(s,e)=>{moves.Items.Clear();foreach(XmlElement m in db.SelectNodes("/SpecialDatabase/Move"))if(m.GetAttribute("character")==characters.Text)moves.Items.Add(new Item{Node=m});if(moves.Items.Count>0)moves.SelectedIndex=0;};moves.SelectedIndexChanged+=(s,e)=>Describe();scenario.SelectedIndexChanged+=(s,e)=>Describe();begin.Click+=(s,e)=>Safe(Begin);finish.Click+=(s,e)=>Safe(Finish);next.Click+=(s,e)=>Safe(Next);FormClosed+=(s,e)=>{if(armed!=null){ValidationSession.Stop();SpecialTrial.Active=false;}};characters.SelectedIndex=0;
 }
 void Safe(Action a){try{a();}catch(Exception e){detail.Text=e.Message;}}
 string ResultPath(XmlElement m,string mode){return Path.Combine(AppPaths.DataDirectory,"special-results",m.GetAttribute("id")+"-"+mode+".xml");}
 void Describe(){var item=moves.SelectedItem as Item;if(item==null)return;var m=item.Node;var b=new StringBuilder();b.AppendLine("ASSISTED TEST: manually selected character/move; native identity remains unmapped.");b.AppendLine("Input (reference): "+m.GetAttribute("input"));b.AppendLine("Properties: "+m.GetAttribute("properties"));b.AppendLine("Scenario: "+scenario.Text);b.AppendLine("Whiff: move out of range. Block: set guard-all and move into range. Hit: turn guard off and move into range.");b.AppendLine("Execute ONE selected move. Let it finish. Include its listed follow-up only when testing that follow-up row.");b.AppendLine("Charge inputs require holding the bracketed direction; no verified charge-duration automation is available.");b.AppendLine("Begin recording, return to Training, perform the move, then Finish + save. Roster selection, positioning and guard setting are manual.");b.AppendLine("No automatic PASS: recovery, stun and actionability remain unverified.");b.AppendLine();foreach(XmlNode n in m.ChildNodes)b.AppendLine("REFERENCE "+n.Name+": "+n.InnerText);string path=ResultPath(m,scenario.Text);if(File.Exists(path)){var saved=new XmlDocument();saved.Load(path);b.AppendLine("LAST TEST: "+saved.DocumentElement.GetAttribute("status"));}detail.Text=b.ToString();}
 void Begin(){var selected=moves.SelectedItem as Item;if(selected==null)return;SpecialTrial.Begin(PipelineDiagnostics.Latest);armed=selected.Node;armedScenario=scenario.Text;detail.Text="Recording "+armed.GetAttribute("name")+" / "+armedScenario+". Return to Training and perform this move once. The trace is saved even if timing never completes.";}
 void Finish(){if(armed==null||!SpecialTrial.Active)throw new InvalidOperationException("Begin a trial first.");ValidationSession.Stop();SpecialTrial.Active=false;var f=SpecialTrial.Latest;var c=f==null?null:f.Meter.Players[0];bool complete=c!=null&&c.LastAttack!=null&&c.LastAttack.Capture>ValidationSession.Start&&!c.TimingInProgress&&ValidationSession.Completions==1;string status=SpecialTrial.Result(armedScenario,complete);var values=complete?SevenMetrics.Values(c,false):new[]{"—","—","—","—","—","—","—"};
  if(!complete||ValidationSession.Broken)values=new[]{"—","—","—","—","—","—","—"};
  var xml=new XmlDocument();var result=xml.CreateElement("SpecialResult");xml.AppendChild(result);foreach(string attr in new[]{"id","character","name","input","row"})result.SetAttribute(attr,armed.GetAttribute(attr));result.SetAttribute("scenario",armedScenario);result.SetAttribute("status",status);result.SetAttribute("identitySource","MANUAL_LABEL_NOT_NATIVE_MAPPING");result.SetAttribute("nativeActions",String.Join(";",SpecialTrial.Actions));result.SetAttribute("trace",ValidationSession.Trace);result.SetAttribute("utc",DateTime.UtcNow.ToString("o"));result.SetAttribute("hit",SpecialTrial.Hit.ToString());result.SetAttribute("guard",SpecialTrial.Guard.ToString());
  var csv=new StringBuilder("Metric,Measured,Reference,Status\r\n");string[] keys={"startup","active","recovery","on_hit","on_block","damage","stun_damage"};for(int i=0;i<7;i++){var el=xml.CreateElement("Metric");el.SetAttribute("name",keys[i]);el.SetAttribute("measured",values[i]);var reference=armed.SelectSingleNode(keys[i]);el.SetAttribute("reference",reference==null?"":reference.InnerText);result.AppendChild(el);csv.AppendLine(String.Join(",",new[]{RosterValidation.Csv(keys[i]),RosterValidation.Csv(values[i]),RosterValidation.Csv(el.GetAttribute("reference")),RosterValidation.Csv("UNVERIFIED_COMPARISON")}));}
  string path=ResultPath(armed,armedScenario);Directory.CreateDirectory(Path.GetDirectoryName(path));xml.Save(Path.ChangeExtension(ValidationSession.Trace,"special-result.xml"));xml.Save(path);File.WriteAllText(Path.ChangeExtension(ValidationSession.Trace,"special-result.csv"),csv.ToString());armed=null;detail.Text="Saved: "+status+"\r\n"+path+"\r\n"+csv+"\r\nExecution is independent of contact; a completed measurement is not certification of all seven fields.";
 }
 void Next(){if(armed!=null)throw new InvalidOperationException("Finish the current trial first.");for(int n=0;n<moves.Items.Count*3;n++){int m=(moves.SelectedIndex*3+scenario.SelectedIndex+1+n)%(moves.Items.Count*3);var item=(Item)moves.Items[m/3];string mode=(string)scenario.Items[m%3];if(!File.Exists(ResultPath(item.Node,mode))){moves.SelectedIndex=m/3;scenario.SelectedIndex=m%3;return;}}detail.Text="Every candidate for this character has a saved trial. Saved does not mean PASS; review incomplete/unverified results before continuing.";}
}
